### ISSUE TITLE
Can't Sync for the first time

### ISSUE THREAD

**Issue by DNAngeluS** [jihh/redmine_ldap_synchronizer#1]
Hi!, I installed the plugin, I can access from Redmine extensions and the only available option is "inactive if not found". I have LDAP Authentication working I've tested it with 3 user without major issues.
When I run the command 
`rake --trace redmine:ldap:synchronize`
 
I get this error
`
** Invoke redmine:ldap:synchronize (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:ldap:synchronize
rake aborted!
NoMethodError: private method `select' called for nil:NilClass
/usr/src/redmine/plugins/redmine_ldap_synchronizer/lib/redmine_ldap_synchronizer/user_patch.rb:26:in 'synchronize_ldap_information'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:432:in 'block in make_lambda'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:164:in 'call'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:164:in 'block in halting'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in 'call'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in 'block in call'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in 'each'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in 'call'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in '__run_callbacks__'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in '_run_save_callbacks'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:302:in 'create_or_update'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:120:in 'save'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:37:in 'save'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:21:in 'save'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:286:in 'block (2 levels) in save'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:351:in 'block in with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in 'block in transaction'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in 'within_new_transaction'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in 'transaction'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in 'transaction'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:348:in 'with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:286:in 'block in save'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:301:in 'rollback_active_record_state!'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:285:in 'save'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:51:in 'block (2 levels) in find_each'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:51:in 'each'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:51:in 'block in find_each'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:124:in 'find_in_batches'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:50:in 'find_each'
/usr/src/redmine/plugins/redmine_ldap_synchronizer/lib/tasks/redmine_ldap_synchronizer.rake:23:in 'block (3 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/task.rb:250:in 'call'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/task.rb:250:in 'block in execute'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/task.rb:250:in 'each'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/task.rb:250:in 'execute'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/task.rb:194:in 'block in invoke_with_call_chain'
/usr/local/lib/ruby/2.2.0/monitor.rb:211:in 'mon_synchronize'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/task.rb:187:in 'invoke_with_call_chain'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/task.rb:180:in 'invoke'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/application.rb:152:in 'invoke_task'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/application.rb:108:in 'block (2 levels) in top_level'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/application.rb:108:in 'each'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/application.rb:108:in 'block in top_level'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/application.rb:117:in 'run_with_threads'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/application.rb:102:in 'top_level'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/application.rb:80:in 'block in run'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/application.rb:178:in 'standard_exception_handling'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/application.rb:77:in 'run'
/usr/local/bundle/gems/rake-12.0.0/exe/rake:27:in '<top (required)>'
/usr/local/bundle/bin/rake:17:in 'load'
/usr/local/bundle/bin/rake:17:in '<main>'
Tasks: TOP => redmine:ldap:synchronize
`

I'll gladly help fixing this issue cause I really need to add bulk update to all LDAP users, but I have no knowledge on ruby, so maybe if I understand whats going on, maybe I can fix it.

Best!

**Comment by adrianohf** [comment]
I'm too! Same problem...

`root@ac332faff240:/usr/src/redmine# rake redmine:ldap:synchronize --trace
** Invoke redmine:ldap:synchronize (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:ldap:synchronize
rake aborted!
NoMethodError: private method `select' called for nil:NilClass
/usr/src/redmine/plugins/redmine_ldap_synchronizer/lib/redmine_ldap_synchronizer/user_patch.rb:26:in `synchronize_ldap_information'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:164:in `block in halting'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `block in call'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `each'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `call'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/callbacks.rb:302:in `create_or_update'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/persistence.rb:120:in `save'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/validations.rb:37:in `save'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/attribute_methods/dirty.rb:21:in `save'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/transactions.rb:286:in `block (2 levels) in save'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/transactions.rb:220:in `transaction'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/transactions.rb:286:in `block in save'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/transactions.rb:285:in `save'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/relation/batches.rb:51:in `each'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/relation/batches.rb:51:in `block in find_each'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/relation/batches.rb:124:in `find_in_batches'
/usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/relation/batches.rb:50:in `find_each'
/usr/src/redmine/plugins/redmine_ldap_synchronizer/lib/tasks/redmine_ldap_synchronizer.rake:23:in `block (3 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.2.1/lib/rake/task.rb:251:in `block in execute'
/usr/local/bundle/gems/rake-12.2.1/lib/rake/task.rb:251:in `each'
/usr/local/bundle/gems/rake-12.2.1/lib/rake/task.rb:251:in `execute'
/usr/local/bundle/gems/rake-12.2.1/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/local/bundle/gems/rake-12.2.1/lib/rake/task.rb:188:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-12.2.1/lib/rake/task.rb:181:in `invoke'
/usr/local/bundle/gems/rake-12.2.1/lib/rake/application.rb:160:in `invoke_task'
/usr/local/bundle/gems/rake-12.2.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/bundle/gems/rake-12.2.1/lib/rake/application.rb:116:in `each'
/usr/local/bundle/gems/rake-12.2.1/lib/rake/application.rb:116:in `block in top_level'
/usr/local/bundle/gems/rake-12.2.1/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/bundle/gems/rake-12.2.1/lib/rake/application.rb:110:in `top_level'
/usr/local/bundle/gems/rake-12.2.1/lib/rake/application.rb:83:in `block in run'
/usr/local/bundle/gems/rake-12.2.1/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/bundle/gems/rake-12.2.1/lib/rake/application.rb:80:in `run'
/usr/local/bundle/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/rake:21:in `load'
/usr/local/bundle/bin/rake:21:in `<main>'
Tasks: TOP => redmine:ldap:synchronize
root@ac332faff240:/usr/src/redmine# `
